[package]
authors=["Earthnuker <earthnuker@gmail.com>"]
name = "level_viewer"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/ReScrap/level_viewer"

[package.metadata.wix]
upgrade-guid = "C281C687-92B2-4DD0-B757-FA6CB11B151A"
path-guid = "A8728CA0-C308-4C48-AB79-47ADC765A5C5"
license = false
eula = false

[profile.release]
# codegen-units = 1
# lto = "thin"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"


[dependencies]
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
anyhow = "1.0.83"
better-panic = "0.3.0"
bilge = "0.2.0"
binrw = "0.14"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive", "env"] }
configparser = { version = "3.0.4", features = ["indexmap"] }
enum-iterator = "2.1.0"
fs-err = "2.11.0"
indexmap = { version = "2.2.6", features = ["serde"] }
ini = "1.3.0"
memmap2 = "0.9.4"
num-derive = "0.4.2"
num-traits = "0.2.19"
regex = "1.10.4"
rhexdump = "0.2.0"
serde = { version = "1.0.201", features = ["derive"] }
steamlocate = "1.2.1"
vfs = "0.12.0"
walkdir = "2.5.0"
# Bevy
bevy = { version = "0.14", default-features = false, features = [
    "bmp",
    "dds",
    "tga",
    "png",
    "bevy_gizmos",
    # "dynamic_linking"
] }
bevy_atmosphere = "0.10"
bevy_egui = "0.28.0"
bevy-inspector-egui = "0.25.0"
iyes_perf_ui = { version = "0.3", features = ["chrono"] }
bevy_editor_cam = "0.3.0"
bevy_mod_raycast = "0.18.0"
smooth-bevy-cameras = "0.12.0"
egui_file = "0.18.0"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.18.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = true
