from_latest_tag = false
ignore_merge_commits = false
generate_mono_repository_global_tag = true
branch_whitelist = [ "main", "release/**" ]
skip_untracked = false
pre_bump_hooks = [
    "cargo test",
    "cargo clippy",
    "cargo build --release",
    "cargo fmt --all",
    "cargo bump {{version}}"
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
